name: Check Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Clone Ramp
        run: git clone https://github.com/kshitijrajsharma/ramp-code-fAIr.git ramp-code

      - name: Install gdown
        run: pip install gdown

      - name: Download Basemodel
        run: gdown --fuzzy https://drive.google.com/file/d/1wvJhkiOrSlHmmvJ0avkAdu9sslFf5_I0/view?usp=sharing

      - name: Unzip and Move Basemodel
        run: unzip checkpoint.tf.zip -d ramp-code/ramp

      - name: Install gdal
        run: |
          sudo apt-get -y install gdal-bin python3-gdal && sudo apt-get -y autoremove && sudo apt-get clean
          pip install gdal==3.4.3

      - name: Install ramp dependecies
        run: |
          cd ramp-code && cd colab && make install
      - name: Navigate to home dir
        run: |
          cd ../.. 
          ls
      - name: Install tensorflow
        run: pip install tensorflow==2.9.2

      - name: Install fair utilities
        run: pip install -e .

      - name: Run test workflow
        run: |
          python test_app.py
