name: Check Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Add ubuntugis ppa
        run:
          sudo add-apt-repository ppa:ubuntugis/ppa && sudo apt-get update

      - name: Install gdal
        run: |
          sudo apt-get -y install gdal-bin python3-gdal && sudo apt-get -y autoremove && sudo apt-get clean
      - name : Clone Ramp 
        run : 
          git clone https://github.com/kshitijrajsharma/ramp-code-fAIr.git ramp-code    
      - name: Install ramp dependecies
        run: |
          cd ramp-code && cd colab && make install 
      - name: Install fair-lib 
        run: |
          cd ../.. 
          pip install -e .
      - name: Run workflow
        run: |
          python test_app.py